// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calcIBD
List calcIBD(CharacterVector& popType, CharacterVector& markerFile, CharacterVector& mapFile, Nullable<DataFrame> evalPos, Nullable<NumericVector> evalDist, const bool& grid, const bool& verbose);
RcppExport SEXP _statgenIBD_calcIBD(SEXP popTypeSEXP, SEXP markerFileSEXP, SEXP mapFileSEXP, SEXP evalPosSEXP, SEXP evalDistSEXP, SEXP gridSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector& >::type popType(popTypeSEXP);
    Rcpp::traits::input_parameter< CharacterVector& >::type markerFile(markerFileSEXP);
    Rcpp::traits::input_parameter< CharacterVector& >::type mapFile(mapFileSEXP);
    Rcpp::traits::input_parameter< Nullable<DataFrame> >::type evalPos(evalPosSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type evalDist(evalDistSEXP);
    Rcpp::traits::input_parameter< const bool& >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(calcIBD(popType, markerFile, mapFile, evalPos, evalDist, grid, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_statgenIBD_calcIBD", (DL_FUNC) &_statgenIBD_calcIBD, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_statgenIBD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
